HOST_NAME = "localhost"
SERVER_PORT = 8080
DB_USERNAME = "DB_USERNAME"
DB_PASSWORD = "DB_PASSWORD"
FLASK_DB = "flask_db"

# POSTGESQL
POSTGRESQL = "postgresql"
POSTGRES_USER = "postgres"
POSTGRES_PASSWORD = "postgres"
POSTGRES_PORT = 5432
DATABASE_NAME = "cor"
USER_TABLE = "Users"
